"""Description:
    This is the most basic example of how to use the Microsoft Agent Framework to create an agent

Azure resources needed:
    - Azure Foundry with a deployed 'gpt-5-nano' model

Config:
    - review that the model set here matches THE NAME for your deployed model in foundry
        example: I have deployed in foundry an instance for 'gpt-5.4-nano' which is called 'gpt-5.4-nano-1'
            so the code below has to be set to 'gpt-5.4-nano-1'
    - set FOUNDRY_URL as system var. This is the URL you get when you deploy models in your Foundry
"""
from agent_framework.foundry import FoundryChatClient
from azure.identity import AzureCliCredential

import asyncio
import os

async def _async_main():
    # example: "https://your-foundry-project.services.ai.azure.com/api/projects/your-project-name"
    foundry_url = os.environ["FOUNDRY_URL"]

    credential = AzureCliCredential()
    client = FoundryChatClient(
        project_endpoint=foundry_url,
        model="gpt-5.4-nano-1",
        credential=credential
    )

    agent = client.as_agent(
        name="HelloAgent",
        instructions="You are a helpful assistant that provides information about Microsoft Agent Framework. Answer questions concisely and accurately."
    )

    # streaming: receive tokens as they are generated by the model
    print("Agent (streaming): ", end="", flush=True)
    async for token in agent.run("What's Microsoft Agent Framework?", stream=True):
        if token.text:
            print(token.text, end="", flush=True)
    print()

def main():
    asyncio.run(_async_main())

if __name__ == "__main__":
    main()