"""Description:
    This is a simple example of how to use the Microsoft Agent Framework to create an agent

Azure resources needed:
    - Azure Foundry with a deployed 'gpt-5-nano' model

Config:
    - review that the model set here matches THE NAME for your deployed model in foundry
        example: I have deployed in foundry an instance for 'gpt-5.4-nano' which is called 'gpt-5.4-nano-1'
            so the code below has to be set to 'gpt-5.4-nano-1'
    - set FOUNDRY_URL as system var. This is the URL you get when you deploy models in your Foundry
"""
from agent_framework import Agent, tool
from agent_framework.foundry import FoundryChatClient
from azure.identity import AzureCliCredential

from typing import Annotated
from pydantic import Field

import asyncio
import os

# <define_tool>
@tool(approval_mode="never_require")
def get_weather(
    location: Annotated[str, Field(description="The location to get the weather for.")],
) -> str:
    """Get the current weather for a given location."""
    # In a real implementation, you would call a weather API here.
    # For this example, we'll just return a dummy weather report.
    return f"The current weather in {location} is sunny with a high of 25°C and a low of 15°C."
# </define_tool>

async def _async_main():
    # example: "https://your-foundry-project.services.ai.azure.com/api/projects/your-project-name"
    foundry_url = os.environ["FOUNDRY_URL"]

    client = FoundryChatClient(
        project_endpoint=foundry_url,
        model="gpt-5.4-nano-1",
        credential=AzureCliCredential()
    )

    agent = Agent(
        client=client,
        name="WeatherAgent",
        instructions="You're a helpful weather agent. Use the get_weather tool to answer questions",
        tools=[get_weather]
    )

    # streaming: receive tokens as they are generated by the model
    print("Agent (streaming): ", end="", flush=True)
    async for token in agent.run("What's the weather today in Madrid?", stream=True):
        if token.text:
            print(token.text, end="", flush=True)
    print()

def main():
    asyncio.run(_async_main())

if __name__ == "__main__":
    main()